import 'package:myapp/image_state.dart';

const List<SignInfo> rallySigns = [
  // Level 1
  SignInfo(
    assetPath: 'assets/level1/001.jpg',
    number: '1',
    name: 'Sit',
    level: 1,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level1/002.jpg',
    number: '2',
    name: 'Sit-Stand',
    level: 1,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level1/003.jpg',
    number: '3',
    name: 'Sit-Down',
    level: 1,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level1/004.jpg',
    number: '4',
    name: 'Sit-Down-Sit',
    level: 1,
    static: 3,
  ),
  SignInfo(
    assetPath: 'assets/level1/005.jpg',
    number: '5',
    name: 'Right Turn',
    level: 1,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level1/006.jpg',
    number: '6',
    name: 'Left Turn',
    level: 1,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level1/007.jpg',
    number: '7',
    name: 'About Turn Right',
    level: 1,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level1/008.jpg',
    number: '8',
    name: 'About Turn Left',
    level: 1,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level1/009.jpg',
    number: '9',
    name: '270 Degree Right Turn',
    level: 1,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level1/010.jpg',
    number: '10',
    name: '360 Degree Right Turn',
    level: 1,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level1/011.jpg',
    number: '11',
    name: 'Call Front - Forward Right',
    level: 1,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level1/012.jpg',
    number: '12',
    name: 'Call Front - Forward Left',
    level: 1,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level1/013.jpg',
    number: '13',
    name: 'Call Front - Finish Right',
    level: 1,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level1/014.jpg',
    number: '14',
    name: 'Call Front - Finish Left',
    level: 1,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level1/015.jpg',
    number: '15',
    name: 'Slow Pace',
    level: 1,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level1/016.jpg',
    number: '16',
    name: 'Fast Pace',
    level: 1,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level1/017.jpg',
    number: '17',
    name: 'Normal Pace',
    level: 1,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level1/018.jpg',
    number: '18',
    name: 'Moving Side Step Right',
    level: 1,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level1/019.jpg',
    number: '19',
    name: 'Sit - Right Turn - Forward',
    level: 1,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level1/020.jpg',
    number: '20',
    name: 'Sit - Left Turn - Forward',
    level: 1,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level1/021.jpg',
    number: '21',
    name: 'Figure 8',
    level: 1,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level1/022.jpg',
    number: '22',
    name: 'Serpentine',
    level: 1,
    static: 0,
  ),

  // Level 2
  SignInfo(
    assetPath: 'assets/level2/023.jpg',
    number: '23',
    name: 'Sit - Walk Around',
    level: 2,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level2/024.jpg',
    number: '24',
    name: 'Sit - Down - Walk Around',
    level: 2,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level2/025.jpg',
    number: '25',
    name: '270 Degree Left Turn',
    level: 2,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level2/026.jpg',
    number: '26',
    name: '360 Degree Left Turn',
    level: 2,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level2/027.jpg',
    number: '27',
    name: 'Sit - 90 Degree Pivot Right - Sit',
    level: 2,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level2/028.jpg',
    number: '28',
    name: 'Sit - 90 Degree Pivot Left - Sit',
    level: 2,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level2/029.jpg',
    number: '29',
    name: 'Sit - Turn Right - 1 Step - Sit',
    level: 2,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level2/030.jpg',
    number: '30',
    name: 'Sit - Turn Left - 1 Step - Sit',
    level: 2,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level2/031.jpg',
    number: '31',
    name: 'Sit - Send Around - Sit',
    level: 2,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level2/032.jpg',
    number: '32',
    name: 'Sit - Send Around - Forward',
    level: 2,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level2/033.jpg',
    number: '33',
    name: 'Spiral Right - Dog Outside',
    level: 2,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level2/034.jpg',
    number: '34',
    name: 'Spiral Left - Dog Inside',
    level: 2,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level2/035.jpg',
    number: '35',
    name: 'Weave Through Distractions',
    level: 2,
    static: 0,
  ),

  // Level 3
  SignInfo(
    assetPath: 'assets/level3/036a.jpg',
    number: '36a',
    name: 'Sit - Leave Dog - Recall - Finish Right',
    level: 3,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level3/036b.jpg',
    number: '36b',
    name: 'Sit - Leave Dog - Recall - Finish Right',
    level: 3,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level3/037a.jpg',
    number: '37a',
    name: 'Sit - Leave Dog - Recall - Finish Left',
    level: 3,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level3/037b.jpg',
    number: '37b',
    name: 'Sit - Leave Dog - Recall - Finish Left',
    level: 3,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level3/039.jpg',
    number: '38',
    name: 'Sit - About Turn Right - Forward',
    level: 3,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level3/038.jpg',
    number: '39',
    name: 'Sit - About Turn Left - Forward',
    level: 3,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level3/038.jpg',
    number: '40',
    name: 'Left About Turn',
    level: 3,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level3/039.jpg',
    number: '41',
    name: 'Down',
    level: 3,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level3/040.jpg',
    number: '42',
    name: 'Stand',
    level: 3,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level3/041.jpg',
    number: '43',
    name: 'Sit - Fast Forward',
    level: 3,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level3/042.jpg',
    number: '44',
    name: 'Sit - Leave Dog - Call To Heel While Moving',
    level: 3,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level3/043.jpg',
    number: '45',
    name: 'Loop Around Distractions',
    level: 3,
    static: 0,
  ),

  // Level 4
  SignInfo(
    assetPath: 'assets/level4/046a.jpg',
    number: '46a',
    name: 'Sit - Leave Dog - Angled Recall - Finish Right Or Left',
    level: 4,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level4/046b.jpg',
    number: '46b',
    name: 'Sit - Leave Dog - Angled Recall - Finish Right Or Left',
    level: 4,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level4/047.jpg',
    number: '47',
    name: 'Sit - 180 Degree Pivot Right - Sit',
    level: 4,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level4/048.jpg',
    number: '48',
    name: 'Sit - 180 Degree Pivot Left - Sit',
    level: 4,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level4/049.jpg',
    number: '49',
    name: 'Sit - Side Step Right - Sit',
    level: 4,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level4/050.jpg',
    number: '50',
    name: 'Stand - Send Around - Forward',
    level: 4,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level4/051.jpg',
    number: '51',
    name: 'Moving Send Around',
    level: 4,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level4/052.jpg',
    number: '52',
    name: 'Stand - Walk Around',
    level: 4,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level4/053.jpg',
    number: '53',
    name: 'Down - Walk Around',
    level: 4,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level4/054a.jpg',
    number: '54a',
    name: 'Sit - Leave Dog - Down On Recall',
    level: 4,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level4/054b.jpg',
    number: '54b',
    name: 'Sit - Leave Dog - Down On Recall',
    level: 4,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level4/055.jpg',
    number: '55',
    name: 'Run Past Jump',
    level: 4,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level4/056a.jpg',
    number: '56a',
    name: 'Sit Leave Dog - Recall Over Jump',
    level: 4,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level4/056b.jpg',
    number: '56b',
    name: 'Sit Leave Dog - Recall Over Jump',
    level: 4,
    static: 1,
  ),

  // Level 5
  SignInfo(
    assetPath: 'assets/level5/057a.jpg',
    number: '57a',
    name: 'Stand - Leave Dog - Turn - Call To Heel',
    level: 5,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level5/057b.jpg',
    number: '57b',
    name: 'Stand - Leave Dog - Turn - Call To Heel',
    level: 5,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level5/058.jpg',
    number: '58',
    name: 'Moving Backup',
    level: 5,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level5/059.jpg',
    number: '59',
    name: 'Send Over Jump - Handler Runs By',
    level: 5,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level5/060.jpg',
    number: '60',
    name: 'Right Turn - 1 or 2 Steps - Down',
    level: 5,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level5/061.jpg',
    number: '61',
    name: 'Left Turn - 1 or 2 Steps - Down',
    level: 5,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level5/062.jpg',
    number: '62',
    name: 'Call Front - About Turn Right - Forward',
    level: 5,
    static: 1,
  ),

  // Level 6
  SignInfo(
    assetPath: 'assets/level6/063a.jpg',
    number: '63a',
    name: 'Stand - Leave Dog - Down - Sit - Recall - Finish',
    level: 6,
    static: 4,
  ),
  SignInfo(
    assetPath: 'assets/level6/063b.jpg',
    number: '63b',
    name: 'Stand - Leave Dog - Down - Sit - Recall - Finish',
    level: 6,
    static: 4,
  ),
  SignInfo(
    assetPath: 'assets/level6/064a.jpg',
    number: '64a',
    name: 'Stand - Leave Dog - Down On Recall - Return',
    level: 6,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level6/064b.jpg',
    number: '64b',
    name: 'Stand - Leave Dog - Down On Recall - Return',
    level: 6,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level6/065a.jpg',
    number: '65a',
    name: 'Down On Move - Recall To Heel - Send Around',
    level: 6,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level6/065b.jpg',
    number: '65b',
    name: 'Down On Move - Recall To Heel - Send Around',
    level: 6,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level6/066a.jpg',
    number: '66a',
    name: 'Sit - Leave Dog - Angled Recall Over Jump',
    level: 6,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level6/066b.jpg',
    number: '66b',
    name: 'Sit - Leave Dog - Angled Recall Over Jump',
    level: 6,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level6/067.jpg',
    number: '67',
    name: 'Right Turn - Backup',
    level: 6,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/level6/068.jpg',
    number: '68',
    name: 'Left Turn - Backup',
    level: 6,
    static: 0,
  ),

  // Bonus
  SignInfo(
    assetPath: 'assets/level1/bonus1.jpg',
    number: 'Bonus Ex. 1',
    name: 'Call Front - Side Step Right Or Left',
    level: 1,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level1/bonus2.jpg',
    number: 'Bonus Ex. 2',
    name: 'Call Front - Turn Right Or Left',
    level: 1,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level1/bonus3.jpg',
    number: 'Bonus Ex. 3',
    name: 'Sit - 3 Steps - Sit',
    level: 1,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level2/bonus4a.jpg',
    number: 'Bonus Ex. 4a',
    name: 'Sit - Leave Dog - Call To Heel',
    level: 2,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level2/bonus4b.jpg',
    number: 'Bonus Ex. 4b',
    name: 'Sit - Leave Dog - Call To Heel',
    level: 2,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level2/bonus5a.jpg',
    number: 'Bonus Ex. 5a',
    name: 'Sit - Leave Dog - Turn - Recall - Handler Finish',
    level: 2,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level2/bonus5b.jpg',
    number: 'Bonus Ex. 5b',
    name: 'Sit - Leave Dog - Turn - Recall - Handler Finish',
    level: 2,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level3/bonus6.jpg',
    number: 'Bonus Ex. 6',
    name: 'Call Front - Backup 3 Steps',
    level: 3,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level3/bonus7a.jpg',
    number: 'Bonus Ex. 7a',
    name: 'Sit - Leave Dog - Turn - Down',
    level: 3,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level3/bonus7b.jpg',
    number: 'Bonus Ex. 7b',
    name: 'Sit - Leave Dog - Turn - Down',
    level: 3,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level3/bonus8a.jpg',
    number: 'Bonus Ex. 8a',
    name: 'Sit - Leave Dog - Recall Through Distractions',
    level: 3,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level3/bonus8b.jpg',
    number: 'Bonus Ex. 8b',
    name: 'Sit - Leave Dog - Recall Through Distractions',
    level: 3,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level4/bonus9a.jpg',
    number: 'Bonus Ex. 9a',
    name: 'Sit - Leave Dog - Turn - Stand',
    level: 4,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level4/bonus9b.jpg',
    number: 'Bonus Ex. 9b',
    name: 'Sit - Leave Dog - Turn - Stand',
    level: 4,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level4/bonus10a.jpg',
    number: 'Bonus Ex. 10a',
    name: 'Turn - Sit - Retrieve - Finish',
    level: 5,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level4/bonus10b.jpg',
    number: 'Bonus Ex. 10b',
    name: 'Turn - Sit - Retrieve - Finish',
    level: 5,
    static: 2,
  ),
  SignInfo(
    assetPath: 'assets/level5/bonus11.jpg',
    number: 'Bonus Ex. 11',
    name: 'Down On The Move - Turn - Return To Dog',
    level: 5,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level5/bonus12.jpg',
    number: 'Bonus Ex. 12',
    name: 'Send Back For Retrieve - Finish',
    level: 6,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/level6/bonus13.jpg',
    number: 'Bonus Ex. 13',
    name: 'Send Around Pole - Loop To Heel - Forward',
    level: 6,
    static: 0,
  ),

  // Base
  SignInfo(
    assetPath: 'assets/base/start.jpg',
    number: '',
    name: 'Start',
    level: 0,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/base/finish.jpg',
    number: '',
    name: 'Finish',
    level: 0,
    static: 1,
  ),
  SignInfo(
    assetPath: 'assets/base/bonus.jpg',
    number: '',
    name: 'Bonus',
    level: 0,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/base/directional_arrow.jpg',
    number: '',
    name: '',
    level: 0,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/base/horizontal_3cones.jpg',
    number: '',
    name: '',
    level: 0,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/base/horizontal_4cones.jpg',
    number: '',
    name: '',
    level: 0,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/base/vertical_3cones.jpg',
    number: '',
    name: '',
    level: 0,
    static: 0,
  ),
  SignInfo(
    assetPath: 'assets/base/vertical_4cones.jpg',
    number: '',
    name: '',
    level: 0,
    static: 0,
  ),
];
